### PR TITLE
logging object

### LINKED ISSUE #219: TestResultsTableViewController.m crash
This crash comes from fabric:
```
Fatal Exception: NSInvalidArgumentException
*** -[__NSDictionaryM setObject:forKey:]: key cannot be nil
```

stacktrace of the error is:

```
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x1d622cec4 __exceptionPreprocess
1  libobjc.A.dylib                0x1d53fda40 objc_exception_throw
2  CoreFoundation                 0x1d61a4494 _CFArgv
3  CoreFoundation                 0x1d6117a0c -[__NSDictionaryM setObject:forKey:]
4  ooniprobe                      0x104be6164 -[TestResultsTableViewController testFilter:] (TestResultsTableViewController.m:39)
5  ooniprobe                      0x104bfa85c __42-[ResultsHeaderViewController reloadQuery]_block_invoke (ResultsHeaderViewController.m:50)
6  libdispatch.dylib              0x1d5c656c8 _dispatch_call_block_and_release
7  libdispatch.dylib              0x1d5c66484 _dispatch_client_callout
8  libdispatch.dylib              0x1d5c45b34 _dispatch_main_queue_callback_4CF$VARIANT$armv81
9  CoreFoundation                 0x1d61bcdf4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
10 CoreFoundation                 0x1d61b7cbc __CFRunLoopRun
11 CoreFoundation                 0x1d61b71f0 CFRunLoopRunSpecific
12 GraphicsServices               0x1d8430584 GSEventRunModal
13 UIKitCore                      0x20350ed40 UIApplicationMain
14 ooniprobe                      0x104beefc8 main (main.m:6)
15 libdyld.dylib                  0x1d5c76bb4 start
```

### PR DESCRIPTION
**Pull request by lorenzoPrimi**
Fixes #219

## Proposed Changes

  - This attempt to fix 219 by ignoring object with nil date. Some tests will disappear but if they have a nil date we can't really put them under a month section.
  - Furthermore will log the object that has this unusual value in this way : https://fabric.io/ooni/ios/apps/org.openobservatory.ooniprobe/issues/5c401ef8f8b88c29638b2055/sessions/latest

### CODE REVIEW

File: ooniprobe/View/TestResults/TestResultsTableViewController.m [hunk 1]
```diff
@@ -35,7 +36,12 @@ -(void)testFilter:(SRKQuery*)newQuery{
         if ([dic objectForKey:key])
             arr = [[dic objectForKey:key] mutableCopy];
         [arr addObject:current];
-        [dic setObject:arr forKey:key];
+        if (key == nil){
+            //log object
+            [CrashlyticsKit recordError:[NSError errorWithDomain:@"key_nill" code:0 userInfo:[current dictionary]]];
```
Comment (bassosimone) [inline ooniprobe/View/TestResults/TestResultsTableViewController.m]: `key_nil` (with only one `l`)?

Comment (bassosimone) [reply ooniprobe/View/TestResults/TestResultsTableViewController.m]: I would assume `userInfo` will be serialised in a way in which we don't see issues?

Comment (lorenzoPrimi) [reply ooniprobe/View/TestResults/TestResultsTableViewController.m]: - `nil` is an alternative way to say `NULL` in obj-c
- Good question, let me set date to nil and send that object
